### ISSUE TITLE
FEATURE REQUEST MULTIPLE DOMAINS w/ SSL FOR A SINGLE IRCD

### ISSUE THREAD

**Issue by nirvanaxo** [ophion-project/ophion#7]
# FEATURE REQUEST MULTIPLE DOMAINS w/ SSL FOR A SINGLE IRCD
So I can have my server be irc.whatever.com and host other websites/projects/irc servers with irc.whatever2.com
when a client connects to irc.whatever2.com server will recognize that and all RAWS/interaction will be by irc.whatever2.com
if somebody connects on irc.whatever.com - same thing, it'll be as if you're connected to that

same server, different domains

**Comment by kaniini** [comment]
this is probably pretty hard to do on the current charybdis-based ircd, but maybe we can consider it in the elixir-based rewrite

**Comment by nirvanaxo** [comment]
sounds good
